name: mindfocus
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.3+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #For Navigation and state package
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  easy_localization: ^3.0.0
  #İmage Design more
  flutter_xlider: ^3.4.0
  flutter_svg: ^0.19.3
  timer_count_down: ^2.0.0
  cupertino_icons: ^1.0.2
  another_flushbar: ^1.10.17
  flutter_staggered_grid_view: ^0.3.4
  #players
  audio_manager: 0.5.5+3
  audioplayers: ^0.18.0
  #backend
  http:
  intl: ^0.17.0
  uuid: ^3.0.2
  facebook_app_events: ^0.11.1
  firebase_analytics: ^7.1.1
  facebook_audience_network: ^0.9.0
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.1
  flutter_facebook_auth: ^3.1.1
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.3
  url_launcher: ^6.0.2
  #firebase_admob: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner:
# flutter pub run build_runner build

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/signpage/google.png
    - assets/signpage/facebook.png
    - assets/signpage/Vector1.png
    - assets/signpage/Vector2.png
    - assets/signpage/Vector3.png
    - assets/signpage/Vector4.png
    - assets/signpage/Vector5.png
    - assets/signpage/Vector6.png
    - assets/logo.jpg
    #Süslemeler
    - assets/susleme/dark/sus_1.svg
    - assets/susleme/dark/sus_2.svg
    - assets/susleme/dark/sus_3.svg
    - assets/susleme/dark/sus_4.svg
    - assets/susleme/dark/sus_5.svg
    - assets/susleme/category_1.svg
    - assets/susleme/category_2.svg
    - assets/susleme/category_3.svg
    - assets/susleme/category_4.svg
    - assets/susleme/category_5.svg
    - assets/susleme/favourite_page_background.svg
    - assets/susleme/favourite.svg
    - assets/susleme/homepage.svg
    #Button_Vectors
    - assets/Button_Vectors/0.svg
    - assets/Button_Vectors/1.svg
    - assets/Button_Vectors/2.svg
    - assets/Button_Vectors/3.svg
    - assets/Button_Vectors/4.svg
    - assets/Button_Vectors/5.svg
    - assets/Button_Vectors/6.svg
    - assets/Button_Vectors/7.svg
    - assets/Button_Vectors/8.svg
    - assets/Button_Vectors/9.svg
    - assets/Button_Vectors/10.svg
    #-----------Dark Buttons-----------#
    - assets/DarkButtons/Nature/v1/icon_1.svg
    - assets/DarkButtons/Nature/v1/icon_2.svg
    - assets/DarkButtons/Nature/v1/icon_3.svg
    - assets/DarkButtons/Nature/v1/icon_4.svg
    - assets/DarkButtons/Nature/v1/icon_5.svg
    - assets/DarkButtons/Nature/v1/icon_6.svg
    - assets/DarkButtons/Nature/v1/icon_7.svg
    - assets/DarkButtons/Nature/v1/icon_8.svg
    - assets/DarkButtons/Nature/v1/icon_9.svg
    #City icons
    - assets/DarkButtons/City/v1/icon_1.svg
    - assets/DarkButtons/City/v1/icon_2.svg
    - assets/DarkButtons/City/v1/icon_3.svg
    - assets/DarkButtons/City/v1/icon_4.svg
    - assets/DarkButtons/City/v1/icon_5.svg
    - assets/DarkButtons/City/v1/icon_6.svg
    - assets/DarkButtons/City/v1/icon_7.svg
    - assets/DarkButtons/City/v1/icon_8.svg
    - assets/DarkButtons/City/v1/icon_9.svg
    #Weather Icons
    - assets/DarkButtons/Weather/v1/icon_1.svg
    - assets/DarkButtons/Weather/v1/icon_2.svg
    - assets/DarkButtons/Weather/v1/icon_3.svg
    - assets/DarkButtons/Weather/v1/icon_4.svg
    - assets/DarkButtons/Weather/v1/icon_5.svg
    - assets/DarkButtons/Weather/v1/icon_6.svg
    - assets/DarkButtons/Weather/v1/icon_7.svg
    - assets/DarkButtons/Weather/v1/icon_8.svg
    - assets/DarkButtons/Weather/v1/icon_9.svg
    #Mind Icons
    - assets/DarkButtons/Mind/v1/icon_1.svg
    - assets/DarkButtons/Mind/v1/icon_2.svg
    - assets/DarkButtons/Mind/v1/icon_3.svg
    - assets/DarkButtons/Mind/v1/icon_4.svg
    - assets/DarkButtons/Mind/v1/icon_5.svg
    - assets/DarkButtons/Mind/v1/icon_6.svg
    - assets/DarkButtons/Mind/v1/icon_7.svg
    - assets/DarkButtons/Mind/v1/icon_8.svg
    - assets/DarkButtons/Mind/v1/icon_9.svg
    #Mix Icons
    - assets/DarkButtons/Mix/v1/icon_1.svg
    - assets/DarkButtons/Mix/v1/icon_2.svg
    - assets/DarkButtons/Mix/v1/icon_3.svg
    - assets/DarkButtons/Mix/v1/icon_4.svg
    - assets/DarkButtons/Mix/v1/icon_5.svg
    - assets/DarkButtons/Mix/v1/icon_6.svg
    - assets/DarkButtons/Mix/v1/icon_7.svg
    - assets/DarkButtons/Mix/v1/icon_8.svg
    - assets/DarkButtons/Mix/v1/icon_9.svg
    #---------Icons V2----------------#
    - assets/DarkButtons/Nature/v2/icon_1a.svg
    - assets/DarkButtons/Nature/v2/icon_2a.svg
    - assets/DarkButtons/Nature/v2/icon_3a.svg
    - assets/DarkButtons/Nature/v2/icon_4a.svg
    - assets/DarkButtons/Nature/v2/icon_5a.svg
    - assets/DarkButtons/Nature/v2/icon_6a.svg
    - assets/DarkButtons/Nature/v2/icon_7a.svg
    - assets/DarkButtons/Nature/v2/icon_8a.svg
    - assets/DarkButtons/Nature/v2/icon_9a.svg
    #City icons
    - assets/DarkButtons/City/v2/icon_1a.svg
    - assets/DarkButtons/City/v2/icon_2a.svg
    - assets/DarkButtons/City/v2/icon_3a.svg
    - assets/DarkButtons/City/v2/icon_4a.svg
    - assets/DarkButtons/City/v2/icon_5a.svg
    - assets/DarkButtons/City/v2/icon_6a.svg
    - assets/DarkButtons/City/v2/icon_7a.svg
    - assets/DarkButtons/City/v2/icon_8a.svg
    - assets/DarkButtons/City/v2/icon_9a.svg
    #Weather Icons
    - assets/DarkButtons/Weather/v2/icon_1a.svg
    - assets/DarkButtons/Weather/v2/icon_2a.svg
    - assets/DarkButtons/Weather/v2/icon_3a.svg
    - assets/DarkButtons/Weather/v2/icon_4a.svg
    - assets/DarkButtons/Weather/v2/icon_5a.svg
    - assets/DarkButtons/Weather/v2/icon_6a.svg
    - assets/DarkButtons/Weather/v2/icon_7a.svg
    - assets/DarkButtons/Weather/v2/icon_8a.svg
    - assets/DarkButtons/Weather/v2/icon_9a.svg
    #Mind Icons
    - assets/DarkButtons/Mind/v2/icon_1a.svg
    - assets/DarkButtons/Mind/v2/icon_2a.svg
    - assets/DarkButtons/Mind/v2/icon_3a.svg
    - assets/DarkButtons/Mind/v2/icon_4a.svg
    - assets/DarkButtons/Mind/v2/icon_5a.svg
    - assets/DarkButtons/Mind/v2/icon_6a.svg
    - assets/DarkButtons/Mind/v2/icon_7a.svg
    - assets/DarkButtons/Mind/v2/icon_8a.svg
    - assets/DarkButtons/Mind/v2/icon_9a.svg
    #Mix Icons
    - assets/DarkButtons/Mix/v2/icon_1a.svg
    - assets/DarkButtons/Mix/v2/icon_2a.svg
    - assets/DarkButtons/Mix/v2/icon_3a.svg
    - assets/DarkButtons/Mix/v2/icon_4a.svg
    - assets/DarkButtons/Mix/v2/icon_5a.svg
    - assets/DarkButtons/Mix/v2/icon_6a.svg
    - assets/DarkButtons/Mix/v2/icon_7a.svg
    - assets/DarkButtons/Mix/v2/icon_8a.svg
    - assets/DarkButtons/Mix/v2/icon_9a.svg
   #-----------FavoriButtons---------------
    # Forest
    - assets/FavoriteButtons/cat1/icon_1.svg
    - assets/FavoriteButtons/cat1/icon_2.svg
    - assets/FavoriteButtons/cat1/icon_3.svg
    - assets/FavoriteButtons/cat1/icon_4.svg
    - assets/FavoriteButtons/cat1/icon_5.svg
    - assets/FavoriteButtons/cat1/icon_6.svg
    - assets/FavoriteButtons/cat1/icon_7.svg
    - assets/FavoriteButtons/cat1/icon_8.svg
    - assets/FavoriteButtons/cat1/icon_9.svg
    #Weather
    - assets/FavoriteButtons/cat2/icon_1.svg
    - assets/FavoriteButtons/cat2/icon_2.svg
    - assets/FavoriteButtons/cat2/icon_3.svg
    - assets/FavoriteButtons/cat2/icon_4.svg
    - assets/FavoriteButtons/cat2/icon_5.svg
    - assets/FavoriteButtons/cat2/icon_6.svg
    - assets/FavoriteButtons/cat2/icon_7.svg
    - assets/FavoriteButtons/cat2/icon_8.svg
    - assets/FavoriteButtons/cat2/icon_9.svg
    #City
    - assets/FavoriteButtons/cat3/icon_1.svg
    - assets/FavoriteButtons/cat3/icon_2.svg
    - assets/FavoriteButtons/cat3/icon_3.svg
    - assets/FavoriteButtons/cat3/icon_4.svg
    - assets/FavoriteButtons/cat3/icon_5.svg
    - assets/FavoriteButtons/cat3/icon_6.svg
    - assets/FavoriteButtons/cat3/icon_7.svg
    - assets/FavoriteButtons/cat3/icon_8.svg
    - assets/FavoriteButtons/cat3/icon_9.svg
    #Mind
    - assets/FavoriteButtons/cat4/icon_1.svg
    - assets/FavoriteButtons/cat4/icon_2.svg
    - assets/FavoriteButtons/cat4/icon_3.svg
    - assets/FavoriteButtons/cat4/icon_4.svg
    - assets/FavoriteButtons/cat4/icon_5.svg
    - assets/FavoriteButtons/cat4/icon_6.svg
    - assets/FavoriteButtons/cat4/icon_7.svg
    - assets/FavoriteButtons/cat4/icon_8.svg
    - assets/FavoriteButtons/cat4/icon_9.svg
    #Mix
    - assets/FavoriteButtons/cat5/icon_1.svg
    - assets/FavoriteButtons/cat5/icon_2.svg
    - assets/FavoriteButtons/cat5/icon_3.svg
    - assets/FavoriteButtons/cat5/icon_4.svg
    - assets/FavoriteButtons/cat5/icon_5.svg
    - assets/FavoriteButtons/cat5/icon_6.svg
    - assets/FavoriteButtons/cat5/icon_7.svg
    - assets/FavoriteButtons/cat5/icon_8.svg
    - assets/FavoriteButtons/cat5/icon_9.svg
   #-----------EditButtons---------------
    # Forest
    - assets/EditButtons/cat1/icon_1.svg
    - assets/EditButtons/cat1/icon_2.svg
    - assets/EditButtons/cat1/icon_3.svg
    - assets/EditButtons/cat1/icon_4.svg
    - assets/EditButtons/cat1/icon_5.svg
    - assets/EditButtons/cat1/icon_6.svg
    - assets/EditButtons/cat1/icon_7.svg
    - assets/EditButtons/cat1/icon_8.svg
    - assets/EditButtons/cat1/icon_9.svg
    #Weather
    - assets/EditButtons/cat2/icon_1.svg
    - assets/EditButtons/cat2/icon_2.svg
    - assets/EditButtons/cat2/icon_3.svg
    - assets/EditButtons/cat2/icon_4.svg
    - assets/EditButtons/cat2/icon_5.svg
    - assets/EditButtons/cat2/icon_6.svg
    - assets/EditButtons/cat2/icon_7.svg
    - assets/EditButtons/cat2/icon_8.svg
    - assets/EditButtons/cat2/icon_9.svg
    #City
    - assets/EditButtons/cat3/icon_1.svg
    - assets/EditButtons/cat3/icon_2.svg
    - assets/EditButtons/cat3/icon_3.svg
    - assets/EditButtons/cat3/icon_4.svg
    - assets/EditButtons/cat3/icon_5.svg
    - assets/EditButtons/cat3/icon_6.svg
    - assets/EditButtons/cat3/icon_7.svg
    - assets/EditButtons/cat3/icon_8.svg
    - assets/EditButtons/cat3/icon_9.svg
    #Mind
    - assets/EditButtons/cat4/icon_1.svg
    - assets/EditButtons/cat4/icon_2.svg
    - assets/EditButtons/cat4/icon_3.svg
    - assets/EditButtons/cat4/icon_4.svg
    - assets/EditButtons/cat4/icon_5.svg
    - assets/EditButtons/cat4/icon_6.svg
    - assets/EditButtons/cat4/icon_7.svg
    - assets/EditButtons/cat4/icon_8.svg
    - assets/EditButtons/cat4/icon_9.svg
    #Mix
    - assets/EditButtons/cat5/icon_1.svg
    - assets/EditButtons/cat5/icon_2.svg
    - assets/EditButtons/cat5/icon_3.svg
    - assets/EditButtons/cat5/icon_4.svg
    - assets/EditButtons/cat5/icon_5.svg
    - assets/EditButtons/cat5/icon_6.svg
    - assets/EditButtons/cat5/icon_7.svg
    - assets/EditButtons/cat5/icon_8.svg
    - assets/EditButtons/cat5/icon_9.svg
   #-----------sesler----------------------
    # Nature Sounds
    - assets/ses/Nature/forest_birds.m4a
    - assets/ses/Nature/forest_fire.m4a
    - assets/ses/Nature/forest_forest.m4a
    - assets/ses/Nature/forest_frogs.m4a
    - assets/ses/Nature/forest_leaves.m4a
    - assets/ses/Nature/forest_river.m4a
    - assets/ses/Nature/forest_selale.m4a
    - assets/ses/Nature/forest_wind.m4a
    - assets/ses/Nature/forest_wolf.m4a
    #Weather Sounds
    - assets/ses/Weather/yumusak_yagmur.m4a
    - assets/ses/Weather/gok_gurultulu_yagmur.m4a
    - assets/ses/Weather/yagmur_cadir.m4a
    - assets/ses/Weather/guclu_yagmur.m4a
    - assets/ses/Weather/yildirim.m4a
    - assets/ses/Weather/dalga.m4a
    - assets/ses/Weather/su_damlasi.m4a
    - assets/ses/Weather/ev_yagmur.m4a
    - assets/ses/Weather/semsiye_yagmur.m4a
    #City Sounds
    - assets/ses/City/tren.m4a
    - assets/ses/City/tramva.m4a
    - assets/ses/City/ucak.m4a
    - assets/ses/City/araba.m4a
    - assets/ses/City/camasir_makinasi.m4a
    - assets/ses/City/klavye.m4a
    - assets/ses/City/fan.m4a
    - assets/ses/City/kafe.m4a
    - assets/ses/City/insanlar.m4a
    #Mind Sounds
    - assets/ses/Mind/piyano.m4a
    - assets/ses/Mind/fulut.m4a
    - assets/ses/Mind/tibet_kasesi.m4a
    - assets/ses/Mind/ruzgar_cani.m4a
    - assets/ses/Mind/taslar.m4a
    - assets/ses/Mind/binaural5.m4a
    - assets/ses/Mind/yesil_nokta.m4a
    - assets/ses/Mind/mavi_nokta.m4a
    - assets/ses/Mind/kirmizi_nokta.m4a
    #Mix Sounds
    - assets/ses/Mix/mix_sonar.m4a
    - assets/ses/Mix/balina_edit.mp3
    - assets/ses/Mix/mix_kalp.m4a
    - assets/ses/Mix/mix_guvercin.m4a
    - assets/ses/Mix/mix_balta.m4a
    - assets/ses/Mix/mix_kuzgun.m4a
    - assets/ses/Mix/mix_sualti.m4a
    - assets/ses/Mix/mix_sayfa.m4a
    - assets/ses/Mix/mix_bicak.m4a


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Effect
      fonts:
        - asset: assets/fonts/Effect.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
