name: mindfocus
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.3+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #For Navigation and state package
  path_provider: ^1.6.5
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  #İmage Design more
  flutter_xlider: ^3.4.0
  flutter_svg: ^0.19.0
  timer_count_down: ^1.0.4+1
  cupertino_icons: ^1.0.0
  flushbar: ^1.10.4
  #players
  audio_manager: 0.5.5+3
  audioplayers: 0.17.2
  http:
  intl: ^0.16.1
  easy_localization: ^2.3.3
  facebook_app_events: ^0.8.2
  #facebook_audience_network: ^0.8.0
  firebase_admob: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/logo.jpg
    - assets/Buttons/Nature/v1/icon_1.svg
    - assets/Buttons/Nature/v1/icon_2.svg
    - assets/Buttons/Nature/v1/icon_3.svg
    - assets/Buttons/Nature/v1/icon_4.svg
    - assets/Buttons/Nature/v1/icon_5.svg
    - assets/Buttons/Nature/v1/icon_6.svg
    - assets/Buttons/Nature/v1/icon_7.svg
    - assets/Buttons/Nature/v1/icon_8.svg
    - assets/Buttons/Nature/v1/icon_9.svg
    #City icons
    - assets/Buttons/City/v1/icon_1.svg
    - assets/Buttons/City/v1/icon_2.svg
    - assets/Buttons/City/v1/icon_3.svg
    - assets/Buttons/City/v1/icon_4.svg
    - assets/Buttons/City/v1/icon_5.svg
    - assets/Buttons/City/v1/icon_6.svg
    - assets/Buttons/City/v1/icon_7.svg
    - assets/Buttons/City/v1/icon_8.svg
    - assets/Buttons/City/v1/icon_9.svg
    #Weather Icons
    - assets/Buttons/Weather/v1/icon_1.svg
    - assets/Buttons/Weather/v1/icon_2.svg
    - assets/Buttons/Weather/v1/icon_3.svg
    - assets/Buttons/Weather/v1/icon_4.svg
    - assets/Buttons/Weather/v1/icon_5.svg
    - assets/Buttons/Weather/v1/icon_6.svg
    - assets/Buttons/Weather/v1/icon_7.svg
    - assets/Buttons/Weather/v1/icon_8.svg
    - assets/Buttons/Weather/v1/icon_9.svg
    #Mind Icons
    - assets/Buttons/Mind/v1/icon_1.svg
    - assets/Buttons/Mind/v1/icon_2.svg
    - assets/Buttons/Mind/v1/icon_3.svg
    - assets/Buttons/Mind/v1/icon_4.svg
    - assets/Buttons/Mind/v1/icon_5.svg
    - assets/Buttons/Mind/v1/icon_6.svg
    - assets/Buttons/Mind/v1/icon_7.svg
    - assets/Buttons/Mind/v1/icon_8.svg
    - assets/Buttons/Mind/v1/icon_9.svg
    #Mix Icons
    - assets/Buttons/Mix/v1/icon_1.svg
    - assets/Buttons/Mix/v1/icon_2.svg
    - assets/Buttons/Mix/v1/icon_3.svg
    - assets/Buttons/Mix/v1/icon_4.svg
    - assets/Buttons/Mix/v1/icon_5.svg
    - assets/Buttons/Mix/v1/icon_6.svg
    - assets/Buttons/Mix/v1/icon_7.svg
    - assets/Buttons/Mix/v1/icon_8.svg
    - assets/Buttons/Mix/v1/icon_9.svg
    #---------Icons V2----------------#
    - assets/Buttons/Nature/v2/icon_1a.svg
    - assets/Buttons/Nature/v2/icon_2a.svg
    - assets/Buttons/Nature/v2/icon_3a.svg
    - assets/Buttons/Nature/v2/icon_4a.svg
    - assets/Buttons/Nature/v2/icon_5a.svg
    - assets/Buttons/Nature/v2/icon_6a.svg
    - assets/Buttons/Nature/v2/icon_7a.svg
    - assets/Buttons/Nature/v2/icon_8a.svg
    - assets/Buttons/Nature/v2/icon_9a.svg
    #City icons
    - assets/Buttons/City/v2/icon_1a.svg
    - assets/Buttons/City/v2/icon_2a.svg
    - assets/Buttons/City/v2/icon_3a.svg
    - assets/Buttons/City/v2/icon_4a.svg
    - assets/Buttons/City/v2/icon_5a.svg
    - assets/Buttons/City/v2/icon_6a.svg
    - assets/Buttons/City/v2/icon_7a.svg
    - assets/Buttons/City/v2/icon_8a.svg
    - assets/Buttons/City/v2/icon_9a.svg
    #Weather Icons
    - assets/Buttons/Weather/v2/icon_1a.svg
    - assets/Buttons/Weather/v2/icon_2a.svg
    - assets/Buttons/Weather/v2/icon_3a.svg
    - assets/Buttons/Weather/v2/icon_4a.svg
    - assets/Buttons/Weather/v2/icon_5a.svg
    - assets/Buttons/Weather/v2/icon_6a.svg
    - assets/Buttons/Weather/v2/icon_7a.svg
    - assets/Buttons/Weather/v2/icon_8a.svg
    - assets/Buttons/Weather/v2/icon_9a.svg
    #Mind Icons
    - assets/Buttons/Mind/v2/icon_1a.svg
    - assets/Buttons/Mind/v2/icon_2a.svg
    - assets/Buttons/Mind/v2/icon_3a.svg
    - assets/Buttons/Mind/v2/icon_4a.svg
    - assets/Buttons/Mind/v2/icon_5a.svg
    - assets/Buttons/Mind/v2/icon_6a.svg
    - assets/Buttons/Mind/v2/icon_7a.svg
    - assets/Buttons/Mind/v2/icon_8a.svg
    - assets/Buttons/Mind/v2/icon_9a.svg
    #Mix Icons
    - assets/Buttons/Mix/v2/icon_1a.svg
    - assets/Buttons/Mix/v2/icon_2a.svg
    - assets/Buttons/Mix/v2/icon_3a.svg
    - assets/Buttons/Mix/v2/icon_4a.svg
    - assets/Buttons/Mix/v2/icon_5a.svg
    - assets/Buttons/Mix/v2/icon_6a.svg
    - assets/Buttons/Mix/v2/icon_7a.svg
    - assets/Buttons/Mix/v2/icon_8a.svg
    - assets/Buttons/Mix/v2/icon_9a.svg
    #-----------Dark Buttons-----------#
    - assets/DarkButtons/Nature/v1/icon_1.svg
    - assets/DarkButtons/Nature/v1/icon_2.svg
    - assets/DarkButtons/Nature/v1/icon_3.svg
    - assets/DarkButtons/Nature/v1/icon_4.svg
    - assets/DarkButtons/Nature/v1/icon_5.svg
    - assets/DarkButtons/Nature/v1/icon_6.svg
    - assets/DarkButtons/Nature/v1/icon_7.svg
    - assets/DarkButtons/Nature/v1/icon_8.svg
    - assets/DarkButtons/Nature/v1/icon_9.svg
    #City icons
    - assets/DarkButtons/City/v1/icon_1.svg
    - assets/DarkButtons/City/v1/icon_2.svg
    - assets/DarkButtons/City/v1/icon_3.svg
    - assets/DarkButtons/City/v1/icon_4.svg
    - assets/DarkButtons/City/v1/icon_5.svg
    - assets/DarkButtons/City/v1/icon_6.svg
    - assets/DarkButtons/City/v1/icon_7.svg
    - assets/DarkButtons/City/v1/icon_8.svg
    - assets/DarkButtons/City/v1/icon_9.svg
    #Weather Icons
    - assets/DarkButtons/Weather/v1/icon_1.svg
    - assets/DarkButtons/Weather/v1/icon_2.svg
    - assets/DarkButtons/Weather/v1/icon_3.svg
    - assets/DarkButtons/Weather/v1/icon_4.svg
    - assets/DarkButtons/Weather/v1/icon_5.svg
    - assets/DarkButtons/Weather/v1/icon_6.svg
    - assets/DarkButtons/Weather/v1/icon_7.svg
    - assets/DarkButtons/Weather/v1/icon_8.svg
    - assets/DarkButtons/Weather/v1/icon_9.svg
    #Mind Icons
    - assets/DarkButtons/Mind/v1/icon_1.svg
    - assets/DarkButtons/Mind/v1/icon_2.svg
    - assets/DarkButtons/Mind/v1/icon_3.svg
    - assets/DarkButtons/Mind/v1/icon_4.svg
    - assets/DarkButtons/Mind/v1/icon_5.svg
    - assets/DarkButtons/Mind/v1/icon_6.svg
    - assets/DarkButtons/Mind/v1/icon_7.svg
    - assets/DarkButtons/Mind/v1/icon_8.svg
    - assets/DarkButtons/Mind/v1/icon_9.svg
    #Mix Icons
    - assets/DarkButtons/Mix/v1/icon_1.svg
    - assets/DarkButtons/Mix/v1/icon_2.svg
    - assets/DarkButtons/Mix/v1/icon_3.svg
    - assets/DarkButtons/Mix/v1/icon_4.svg
    - assets/DarkButtons/Mix/v1/icon_5.svg
    - assets/DarkButtons/Mix/v1/icon_6.svg
    - assets/DarkButtons/Mix/v1/icon_7.svg
    - assets/DarkButtons/Mix/v1/icon_8.svg
    - assets/DarkButtons/Mix/v1/icon_9.svg
    #---------Icons V2----------------#
    - assets/DarkButtons/Nature/v2/icon_1a.svg
    - assets/DarkButtons/Nature/v2/icon_2a.svg
    - assets/DarkButtons/Nature/v2/icon_3a.svg
    - assets/DarkButtons/Nature/v2/icon_4a.svg
    - assets/DarkButtons/Nature/v2/icon_5a.svg
    - assets/DarkButtons/Nature/v2/icon_6a.svg
    - assets/DarkButtons/Nature/v2/icon_7a.svg
    - assets/DarkButtons/Nature/v2/icon_8a.svg
    - assets/DarkButtons/Nature/v2/icon_9a.svg
    #City icons
    - assets/DarkButtons/City/v2/icon_1a.svg
    - assets/DarkButtons/City/v2/icon_2a.svg
    - assets/DarkButtons/City/v2/icon_3a.svg
    - assets/DarkButtons/City/v2/icon_4a.svg
    - assets/DarkButtons/City/v2/icon_5a.svg
    - assets/DarkButtons/City/v2/icon_6a.svg
    - assets/DarkButtons/City/v2/icon_7a.svg
    - assets/DarkButtons/City/v2/icon_8a.svg
    - assets/DarkButtons/City/v2/icon_9a.svg
    #Weather Icons
    - assets/DarkButtons/Weather/v2/icon_1a.svg
    - assets/DarkButtons/Weather/v2/icon_2a.svg
    - assets/DarkButtons/Weather/v2/icon_3a.svg
    - assets/DarkButtons/Weather/v2/icon_4a.svg
    - assets/DarkButtons/Weather/v2/icon_5a.svg
    - assets/DarkButtons/Weather/v2/icon_6a.svg
    - assets/DarkButtons/Weather/v2/icon_7a.svg
    - assets/DarkButtons/Weather/v2/icon_8a.svg
    - assets/DarkButtons/Weather/v2/icon_9a.svg
    #Mind Icons
    - assets/DarkButtons/Mind/v2/icon_1a.svg
    - assets/DarkButtons/Mind/v2/icon_2a.svg
    - assets/DarkButtons/Mind/v2/icon_3a.svg
    - assets/DarkButtons/Mind/v2/icon_4a.svg
    - assets/DarkButtons/Mind/v2/icon_5a.svg
    - assets/DarkButtons/Mind/v2/icon_6a.svg
    - assets/DarkButtons/Mind/v2/icon_7a.svg
    - assets/DarkButtons/Mind/v2/icon_8a.svg
    - assets/DarkButtons/Mind/v2/icon_9a.svg
    #Mix Icons
    - assets/DarkButtons/Mix/v2/icon_1a.svg
    - assets/DarkButtons/Mix/v2/icon_2a.svg
    - assets/DarkButtons/Mix/v2/icon_3a.svg
    - assets/DarkButtons/Mix/v2/icon_4a.svg
    - assets/DarkButtons/Mix/v2/icon_5a.svg
    - assets/DarkButtons/Mix/v2/icon_6a.svg
    - assets/DarkButtons/Mix/v2/icon_7a.svg
    - assets/DarkButtons/Mix/v2/icon_8a.svg
    - assets/DarkButtons/Mix/v2/icon_9a.svg
   #-----------sesler----------------------
    # Nature Sounds
    - assets/ses/Nature/forest_birds.m4a
    - assets/ses/Nature/forest_fire.m4a
    - assets/ses/Nature/forest_forest.m4a
    - assets/ses/Nature/forest_frogs.m4a
    - assets/ses/Nature/forest_leaves.m4a
    - assets/ses/Nature/forest_river.m4a
    - assets/ses/Nature/forest_selale.m4a
    - assets/ses/Nature/forest_wind.m4a
    - assets/ses/Nature/forest_wolf.m4a
    #Weather Sounds
    - assets/ses/Weather/yumusak_yagmur.m4a
    - assets/ses/Weather/gok_gurultulu_yagmur.m4a
    - assets/ses/Weather/yagmur_cadir.m4a
    - assets/ses/Weather/guclu_yagmur.m4a
    - assets/ses/Weather/yildirim.m4a
    - assets/ses/Weather/dalga.m4a
    - assets/ses/Weather/su_damlasi.m4a
    - assets/ses/Weather/ev_yagmur.m4a
    - assets/ses/Weather/semsiye_yagmur.m4a
    #City Sounds
    - assets/ses/City/tren.m4a
    - assets/ses/City/tramva.m4a
    - assets/ses/City/ucak.m4a
    - assets/ses/City/araba.m4a
    - assets/ses/City/camasir_makinasi.m4a
    - assets/ses/City/klavye.m4a
    - assets/ses/City/fan.m4a
    - assets/ses/City/kafe.m4a
    - assets/ses/City/insanlar.m4a
    #Mind Sounds
    - assets/ses/Mind/piyano.m4a
    - assets/ses/Mind/fulut.m4a
    - assets/ses/Mind/tibet_kasesi.m4a
    - assets/ses/Mind/ruzgar_cani.m4a
    - assets/ses/Mind/taslar.m4a
    - assets/ses/Mind/binaural5.m4a
    - assets/ses/Mind/yesil_nokta.m4a
    - assets/ses/Mind/mavi_nokta.m4a
    - assets/ses/Mind/kirmizi_nokta.m4a
    #Mix Sounds
    - assets/ses/Mix/mix_sonar.m4a
    - assets/ses/Mix/balina_edit.mp3
    - assets/ses/Mix/mix_kalp.m4a
    - assets/ses/Mix/mix_guvercin.m4a
    - assets/ses/Mix/mix_balta.m4a
    - assets/ses/Mix/mix_kuzgun.m4a
    - assets/ses/Mix/mix_sualti.m4a
    - assets/ses/Mix/mix_sayfa.m4a
    - assets/ses/Mix/mix_bicak.m4a
    #Süslemeler
    - assets/susleme/light/sus_1.svg
    - assets/susleme/light/sus_2.svg
    - assets/susleme/light/sus_3.svg
    - assets/susleme/light/sus_4.svg
    - assets/susleme/light/sus_5.svg
    - assets/susleme/dark/sus_1.svg
    - assets/susleme/dark/sus_2.svg
    - assets/susleme/dark/sus_3.svg
    - assets/susleme/dark/sus_4.svg
    - assets/susleme/dark/sus_5.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
